# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
imports:
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@CoreBundle/Resources/config/services.yml" }
    - { resource: "@ApiBundle/Resources/config/services.yml" }